source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "just-the-docs", "~> 0.10"
# just-the-docs 0.10+ requires Dart Sass (jekyll-sass-converter >= 3.0).
gem "jekyll-sass-converter", "~> 3.0"

group :jekyll_plugins do
  gem "jekyll-seo-tag"
end
